version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
      - mkdir -p /codebuild/output/src1036931444/src/MKWebApp
      - cp -R build/* /codebuild/output/src1036931444/src/MKWebApp/
artifacts:
  files:
    - '**/*'
  base-directory: /codebuild/output/src1036931444/src/MKWebApp

